export const IO_ICONS: Record<string, string> = {
  'Enhance Accuracy': 'IO_Accuracy.png',
  'Enhance Damage': 'IO_Damage.png',
  'Enhance Defense DeBuff': 'IO_Defense_DeBuff.png',
  'Reduce Endurance Cost': 'IO_Endurance_Reduction.png',
  'Enhance Recharge Speed': 'IO_Recharge_Reduction.png',
  'Enhance Threat Duration': 'IO_Taunt_and_Placate_Duration.png',
  'Enhance KnockBack': 'IO_Knockback_Distance.png',
  'Enhance Disorient': 'IO_Disorient_Duration.png',
  'Enhance Endurance Modification': 'IO_Endurance_Modification.png',
  'Enhance Heal': 'IO_Healing_and_Absorb.png',
  'Enhance Hold': 'IO_Hold_Duration.png',
  'Enhance Confuse': 'IO_Confusion_Duration.png',
  'Enhance Defense': 'IO_Defense_Buff.png',
  'Enhance Fear': 'IO_Fear_Duration.png',
  'Enhance Flying Speed': 'IO_Flight_Speed.png',
  'Enhance Immobilization': 'IO_Immobilization_Duration.png',
  'Enhance Intangibility': 'IO_Intangibility.png',
  'Reduce Interrupt Time': 'IO_Interrupt_Duration.png',
  'Enhance Jump': 'IO_Jumping.png',
  'Enhance Range': 'IO_Range_Increase.png',
  'Enhance Damage Resistance': 'IO_Resist_Damage.png',
  'Enhance Running Speed': 'IO_Run_Speed_Increase.png',
  'Enhance Sleep': 'IO_Sleep_Duration.png',
  'Enhance Slow Movement': 'IO_Slow.png',
  'Enhance ToHit Buffs': 'IO_To_Hit_Buff.png',
  'Enhance ToHit DeBuffs': 'IO_To_Hit_DeBuff.png',
};
